### ISSUE TITLE
Floating panels

### ISSUE THREAD

**Issue by LucaGabi** [givanz/VvvebJs#10]
Hi,

   Great project, I've just started something similar and now I came across this project. My idea is bit different: I only show the page that one will modify and a floating menu that opens  different contexts like a code editor or a css editor or a components palette just not to clutter the work surface. I also have a template engine (x) that I can build components with, it looks like this:

in principiu sunt:
- xblock xinclude sa incluzi component
- xblock xinclude xres sa incluzi resurse ale unui component unde vrei in pagina
- xvar sa definesti resurse
- xif expresie sa afisezi un bloc sau nu
- xfor parcurge o colectie; 
- {{ }} evalueaza expresie js
- $ reprezinta contextul componentului unde gasesti parametrii si data-source-ul asociat

Ex:
    <xblock xinclude="nav" xds="nav" />

    <xblock xinclude="nav" xds="nav" />

    <xblock xres="numevar" xinclude="nav"  />

    <tag xif="jsboolexp">
    </tag>

    <tag xfor="$.posts" xv="post">
        {{post`}}
    </tag>

    <tag xfor="$.posts" xk="i">
        {{$.posts[i]}}
    </tag>

    <tag xfor="$.posts" xv="post" xk="i">
    
    </tag>

TODO:

    <tag xfor="-5:9" xv="u" xk="i">
    
    </tag>
 
I used nodejs for server side and x template engine is build on html extended attributes and tags and {{}} to evaluate js expressions.

Q: Do you want us to try merge the tow projects ? 

I plan to use monaco editor from MS to edit my content and provide js/ts intelisense for datasources and templates and make sort of a development IDE on web.

![image](https://user-images.githubusercontent.com/37976898/43764840-32267134-9a37-11e8-8cfc-0b6c5b0dee42.png)

**Comment by givanz** [comment]
Hi

Thank you, two panels are more easy to use even if they use more space, not a problem on a desktop but it might be on tablets, I might add a new option to use just one panel in the future. 

Floating panels need more clicks to perform an action even if they save space and I don't think they save too much space by removing the visible panels.

The editor only handles html, this makes the code simple by leaving the rendering to the browser.
I think that a better approach is to have a server side template engine that also uses html by processing html tags, for example by using https://github.com/givanz/psttt you can use 

```css
[data-post] [data-post-title] = $post['title']
[data-post] [data-post-date] = $post['date']
```

```html
<div data-post>
   <span data-post-title>this title will be overwritten from db</span>
   <span data-post-date>date placeholder</span>
</div>
```

and in VvvebJs you only need to handle the data attributes.

Thanks for the offer but I plan to keep VvvebJs as simple as possible and for this I need to stick to html editing only.
