### ISSUE TITLE
Extended functions

### ISSUE THREAD

**Issue by dieselpilot** [givanz/VvvebJs#11]
Hey Givan, 

Love this project - really great tool and excellent idea! I'm not technical so forgive the questions but looking for some basic info on the following:

1) In the demo, I am unable to execute JS functions when in preview mode (by copy and paste into code editor). Is this possible?

2) Can pages be linked together to create click through from buttons?

3) Do you have example of script which will allow pages to be saved to server?

I have lots more questions, but will leave it here for now. Thanks for the help!

**Comment by givanz** [comment]
Hi

Thank you.

1 I added a checkbox "Run code on edit" for running js code when editing in the last commit.

2 You mean edit more pages and link them together to create a complete website? If the pages are in the same folder then when editing the link you can set as the url only the filename (ex mypage.html)

Probably what you want is a select input to select the available pages in file manager as the url, you can do this by adding a new input in inputs.js and then change the input type for links in bootstrap4.js

3 Please see this https://github.com/givanz/VvvebJs/issues/12 for a basic solution

**Comment by givanz** [comment]
Hi

Preview does not restart javascript on page or reload the page, it only hides panels.

I guess hopscotch can be added on any page including the editor easily by following the hopscotch documentation, I don't think there is anything specific or any incompatibility with the editor.
