### ISSUE TITLE
server side support

### ISSUE THREAD

**Issue by jamesnfl** [givanz/VvvebJs#12]
Hello..

Looks a great project.
Can you please give me basic idea on how to save user inputs on server side.
I  plan to integrate with php/laravel framework.

@givanz Any ideas will be helpful?

**Comment by givanz** [comment]
Hi

You can get the whole html by calling Vvveb.Builder.getHtml() if you want to save the html page to a file you can replace Vvveb.Gui.save in builder.js line 1144
```js
	save : function () {
		$('#textarea-modal textarea').val(Vvveb.Builder.getHtml());
		$('#textarea-modal').modal();
	},
```
to
```js
  	save : function () {
		
		$.ajax({
		  method: "POST",
		  url: "myphp.php",
		  data: { htmlCode: Vvveb.Builder.getHtml()}
		});		
		
	},
```
and a simple php script to save the contents to a file

```php
<?php
file_put_contents('/path/to/file.html', $_POST['htmlCode']);
```
If you want to save input values then you need to edit inputs.js and edit Input.Setvalue and add a ajax call

```js
var Input = {
	
	setValue: function(value) {
		$('input', this.element).val(value);

		$.ajax({
		  method: "POST",
		  url: "myphp.php",
		  data: { inputValue: value, inputName:$('input', this.element).attr("name")}
		});	
	},
}
```

Some inputs override setValue you will need to add a ajax call to those also but default Input covers most of them.

**Comment by jamesnfl** [comment]
That helps!.. thanks a lot.

**Comment by hirenwadhiya** [comment]
@givanz ,
I tried the above code on my laravel(version 7.6.2) website and I got the "CSRF token mismatch" error. 
To solve that error, I tried:

HTML(in the blade view of blog/index.html):
`<meta name="csrf-token" content="{{ csrf_token() }}" />`

Javascript(libs/builder/builder.js  line: 1463):
`$.ajax({
            method: "POST",
            url: "admin/article/store",
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data: {
                htmlCode: Vvveb.Builder.getHtml()
            }
        });`

Can you please tell me what is wrong with this code setup?

**Comment by armghan3071** [comment]
you can create a custom function with can take a parameter for '**CSRF Token**' and then pass it.

**Comment by 23naresh** [comment]
i need to integrate Vvveb builder with laravel please help

**Comment by armghan3071** [comment]
> i need to integrate Vvveb builder with laravel please help. already i built a template from scratch i need to integrate with my template

Can you share your code here?
