### ISSUE TITLE
editor.html is not working after i download.

### ISSUE THREAD

**Issue by bleedweedsuz** [givanz/VvvebJs#145]
after i download and also clone the project and run the editor.html it does not work like in the [Demo](http://www.vvveb.com/vvvebjs/editor.html).

**Comment by bleedweedsuz** [comment]
i found the solution only after putting in server or local server this project works. 
I think may be it need index.html file.

May be in documentation you guys need to add works in server situation or need to set proper path for index.html file or other info.

p.s. great awesome editor

**Comment by C-h-arles** [comment]
Hi,

I do not understand exactly where to provide the index.html file ?
