### ISSUE TITLE
Init Problem:  Cannot set property 'src' of undefined ...

### ISSUE THREAD

**Issue by Masegi** [givanz/VvvebJs#15]
Hey, first thanks for your amazing work, I would rly like to use it in one of my admin panels, but I have problems initializing the editor.

I followed your usage instructions, but I get this error:

`jquery.min.js:2 jQuery.Deferred exception: Cannot set property 'src' of undefined TypeError: Cannot set property 'src' of undefined
    at Object._loadIframe (https://www.db-app.com/VvvebJs/libs/builder/builder.js:568:19)
    at Object.init (https://www.db-app.com/VvvebJs/libs/builder/builder.js:504:8)
    at HTMLDocument.<anonymous> (https://www.db-app.com/?edit:121:21)
    at j (https://www.db-app.com/VvvebJs/js/jquery.min.js:2:29999)
    at k (https://www.db-app.com/VvvebJs/js/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
12:35:01.466 jquery.min.js:2 Uncaught TypeError: Cannot set property 'src' of undefined
    at Object._loadIframe (builder.js:568)
    at Object.init (builder.js:504)
    at HTMLDocument.<anonymous> (?edit:121)
    at j (jquery.min.js:2)`

I tried debugging it a bit, and it seems like the iframe/canvas is not created, what am I doing wrong?

regards matthias

**Comment by givanz** [comment]
Hi

Thank you, from the error it seems that the iframe element is not found, if you made changes to editor.html make sure that the iframe can be found with selector "#iframe-wrapper > iframe" you can run $("#iframe-wrapper > iframe") in browser console (F12) to see if the the element is found.

Another cause might be different subdomain of the iframe url, make sure that the url that is edited is on the same subdomain or set document.domain to avoid Same-origin policy issues https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by Masegi** [comment]
oh wait, I have to include the editor.html myself? I though it's a template getting used in background.

thanks for your fast response.

**Comment by Masegi** [comment]
ok I think it's working now, but am I right that there is no option to add an background image to a section/div?

**Comment by givanz** [comment]
Thanks for the suggestion, I added background image property for html elements in the last commit https://github.com/givanz/VvvebJs/commit/2eba2ff64b69aeed8ecbb43f0f6968b94e3141f2

**Comment by sagar-kumar-gh** [comment]
hi, @givanz I am trying to implement VvvebJs with **react+next** js its stuck in the same error. I have already tried the above solution but still not working for me, please help me with the issues.

```
import React from "react";
import _JSXStyle from "styled-jsx/style";
import Head from "next/head";
import HtmlEditor from "../public/editor-html/index.html"

export default class TypeWriter extends React.Component {
  componentDidMount() {
    setTimeout(() => {
      Vvveb.Builder.init(HtmlEditor, function () {
        //load code after page is loaded here
        Vvveb.Gui.init();
      });
    }, 1000);
  }
  render() {
    return (
      <div id="mainEditor">
        <Head>
          <script src="/editor-js/jquery.min.js"></script>
          <script src="/editor-js/jquery.hotkeys.js"></script>
          <script src="/editor-js/popper.min.js"></script>
          <script src="/editor-js/bootstrap.min.js"></script>
          <script src="/editor-libs/builder/builder.js"></script>
          <script src="/editor-libs/builder/undo.js"></script>
          <script src="/editor-libs/builder/inputs.js"></script>
          <script src="/editor-libs/builder/components-bootstrap5.js"></script>
          <script src="/editor-libs/builder/components-widgets.js"></script>
          <script src="libs/builder/plugin-codemirror.js"></script>
        </Head>
      </div>
    );
  }
}

```


![VvvebJs](https://user-images.githubusercontent.com/109337948/180382700-22d1d981-757f-447e-8103-19fe05f3c999.png)

**Comment by givanz** [comment]
I guess that `src` is the attribute of the `<iframe>` where the page is loaded, make sure that the html from editor.html that includes the `<iframe>` code is loaded in the page, probably the element is not present and the iframe selector returns `undefined`.
