### ISSUE TITLE
position absolute support?

### ISSUE THREAD

**Issue by 0x410c** [givanz/VvvebJs#16]
i want to postion divs absolute inside a relative div?

is it possible?

**Comment by givanz** [comment]
Hi

You can make any element position absolute (or relative) from display > position then you can change top/left/right/bottom

![absolute](https://user-images.githubusercontent.com/302738/44948775-851f1180-ae2c-11e8-8afe-66576d2d4814.png)

**Comment by MACscr** [comment]
This does not appear to work well. Why dont you make the absolute positioned element actually drag and drop from its current position. Should be able to position it anywhere you want within that parent div with a drag of the mouse.
