### ISSUE TITLE
Uncaught ReferenceError: url is not defined

### ISSUE THREAD

**Issue by javaskript** [givanz/VvvebJs#163]
Using the editor as editor.php, the PHP code at the end uncommented.
Upon making a new page, after clicking "Create Page", this error is thrown:

> VM2808:3 Uncaught ReferenceError: url is not defined
>     at eval (eval at tmpl (builder.js:34), <anonymous>:3:91)
>     at tmpl (builder.js:51)
>     at Object.addPage (builder.js:1906)
>     at HTMLFormElement.<anonymous> (builder.js:1635)
>     at HTMLFormElement.dispatch (jquery.min.js:2)
 >    at HTMLFormElement.y.handle (jquery.min.js:2)

**Comment by givanz** [comment]
Hi

Thanks for the bug report, I changed create page code in the last commit.

**Comment by javaskript** [comment]
Great, thanks!
