### ISSUE TITLE
Input type textbox reuired checkbox not checked existing value

### ISSUE THREAD

**Issue by vktatak** [givanz/VvvebJs#168]
We are trying to make required based on the property .
But old property what given checking in the time required checkbox not selected.

`	<script id="vvveb-input-checkboxinput" type="text/html">

	<div class="custom-control custom-checkbox">
		  <input name="{%=key%}" class="custom-control-input" type="checkbox" id="{%=key%}_check" >
		  <label class="custom-control-label" for="{%=key%}_check">{% if (typeof text !== 'undefined') { %} {%=text%} {% } %}</label>
	</div>
	
</script>`

I checked the checkbox input not working in the editor. Please have a look.

**Comment by vktatak** [comment]
![image](https://user-images.githubusercontent.com/34767618/93183245-60b6d900-f758-11ea-8de7-3eb0ef9d4e0a.png)
![image](https://user-images.githubusercontent.com/34767618/93183312-762c0300-f758-11ea-8c8a-68a8d8da8225.png)

after again same text box click in the time checkbox not checked.

**Comment by givanz** [comment]
Hi

Thanks for the bug report, I fixed checkbox input set value in the last commit.

**Comment by vktatak** [comment]
It's working fine. Great Job!
