### ISSUE TITLE
wbuild.dev

### ISSUE THREAD

**Issue by wbuild-dev** [givanz/VvvebJs#169]
Firstly thanks to this library built by @givanz 

I have built [wbuild.dev](https://wbuild.dev) website builder on top of VvvebJs with some different features. 

- Store files on gitlab or github 
- Deploy to gitlab or github pages
- Using bulma instead of bootstrap
- Themes and templates to start a project
- Fontawsome, Google fonts integration

You can create a project freely or create issue [here](https://github.com/wbuild-dev/wbuild) 

Thanks

**Comment by oleteacher** [comment]
Is this an advertisement?

**Comment by Spaceghost** [comment]
https://opencollective.com/vvvebjs is a great place for you to start contributing back if code isn't your thing.

**Comment by wbuild-dev** [comment]
Code is open source and anyone can develop it with different directions and features as I did with giving the credit to the original source and author.

**Comment by Spaceghost** [comment]
It would be appreciated if you would contribute code upstream or make monetary contributions if you plan on using this open source project's issue tracker as an advertisement platform.

**Comment by Spaceghost** [comment]
Is it? Where’s the source for wbuild?

Please contribute open source patches back to vvveb or contribute
monetarily to the project if you’re also going to use it’s issue tracker as
an ad platform 😉

**Comment by wbuild-dev** [comment]
You can't force anyone to make monetary contribution or code contribution for an open source project. I am sure you are not doing that as well for all the open source project that you are using. And based on license code is also does not necceraily have to be open source. I advise you to research more on this.

This issue is not an advertimesment it is mainly to let the vvveb users know. wbuild.dev has built based on my needs and anyone can use it freely. It is not replacement of vvveb rather alternative with its features.

**Comment by Spaceghost** [comment]
Thank you for closing the issue in this open source project. Good luck on
your project, but it’s bad optics to not contribute anything and use GitHub
issues to boost your non open source work. Try hacker news perhaps.
