### ISSUE TITLE
Migrate from Apache to MIT license, like Bootstrap did

### ISSUE THREAD

**Issue by marclaporte** [givanz/VvvebJs#185]
I suggest to do as Bootstrap did:
https://github.com/twbs/bootstrap/issues/2054

Thanks!

Marc

**Comment by marclaporte** [comment]
@givanz: are you confortable with this?

Thanks!

**Comment by givanz** [comment]
From the Bootstrap discussion it seems that the reason is the incompatibility of APLv2 with GPLv2 license but this seems to be solved in GPLv3.

APLv2 has some advantages like patent protection.

They are very similar licenses, what will be the advantage to relicense to MIT except the GPLv2 compatibility?

**Comment by marclaporte** [comment]
Compatibility with GPLv2 yes, but also compatibility with other licenses such as LGPLv2, MIT, etc. which are uses in countless projects.

**Comment by givanz** [comment]
APLv2 is compatible with MIT, with GPL and LGPL the patent issue is solved in v3.

**Comment by givanz** [comment]
I think that by including it's meant relicense.

Because MIT has less requirements than APLv2 the code can be relicensed to APLv2.

But because APLv2 has requirements like the patent protection that MIT lacks the code can't be relicensed as MIT.

APLv2 code can be included in a MIT project as long as the APLv2 license is kept.

**Comment by marclaporte** [comment]
You write: "APLv2 code can be included in a MIT project as long as the APLv2 license is kept."

Can you share some references supporting this? I am a little fuzzy here. By this logic: why couldn't Bootstrap (when it was APLv2) be included in GPLv2 or LGPLv2 projects (as long as the APLv2 license was kept)? (But of course, different licenses could have different clauses about this...)

"An arrow from box A to box B means that you can combine software with these licenses;"
https://dwheeler.com/essays/floss-license-slide.html

MPL has a clause on this topic "under the terms of the MPL, it allows the integration of MPL-licensed code into proprietary codebases, but only on condition those components remain accessible." Source: https://en.wikipedia.org/wiki/Mozilla_Public_License

**Comment by givanz** [comment]
>  By this logic: why couldn't Bootstrap (when it was APLv2) be included in GPLv2 or LGPLv2 projects

According to this https://www.gnu.org/licenses/license-list.html#apache2 and the Bootstrap thread it was because of the patent requirements.

GPLv3 and MIT doesn't have this incompatibility.

**Comment by marclaporte** [comment]
https://www.gnu.org/licenses/license-list.html#apache2 says "Please note that this license is not compatible with GPL version 2, because it has some requirements that are not in that GPL version."

You wrote: "APLv2 code can be included in a MIT project as long as the APLv2 license is kept."

So let's say https://github.com/concretecms/concretecms/ (MIT license) wants to use VvvebJs: you are saying that they could do so by keeping the code separate and keeping the APLv2 license on each file. (I am not talking about relicensing but just using the code)

Do you have a reference for this? I am trying to understand why a MIT licensed project would be OK with including some code (keeping the headers) with additional requirements while other licenses would not permit it. Is there something specific to GPL2 that prevents this?

FYI: My primary concern is to be able to use VvvebJs in https://gitlab.com/tikiwiki/tiki/ (LGPL 2.1) but I am involved in many projects (with diverse OSI-approved licenses) so I want to understand how this works.

Thanks!

**Comment by givanz** [comment]
I don't know what is the nature of the conflict between GPL2 and the APLv2 patent clause, you probably need to ask someone with deeper knowledge on the subject.

You can upgrade to LGPL3 to avoid this issue.

**Comment by marclaporte** [comment]
> You can upgrade to LGPL3 to avoid this issue.

For any large community project, changing a license is a delicate issue and exposes a diversity of opinions. In our case, it is very unlikely to happen.

Thank you very much for all your feedback and consideration on the matter.

VvvebJs is a very impressive project. Congrats!
