### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by milanstamenkovic** [givanz/VvvebJs#19]
Hi there,

Is there a chance to use VvvebJs inside an angular 6 application? And if you can navigate me to some examples or tutorials?

Thanks in advance, 
Milan

**Comment by givanz** [comment]
Hi

I'm not familiar with angular, VvvebJs uses only jQuery so it will probably not be an issue to integrate it.

**Comment by Linkmetal** [comment]
I've been trying to integrate it on angular (I'm not very experienced on it) and I need a *.d.ts file to declare the module ir order to make it works on Typescript. I've been trying to create it with some generator tools but didn't works.

Anyone has been able to integrate it properly? I appreciate any kind of help.

Thanks in advance.
