### ISSUE TITLE
Video and Maps iFrame

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#2]
First, great job on VvvebJa!

When adding videos (or maps) they are inserted with values 100% width and 100% height. The 100% height does not work as iframes do not scale like images. You end up with very wide video with tiny height.

Maybe this stackoverflow issue can better explain what I mean:

https://stackoverflow.com/questions/38270661/displaying-a-youtube-video-with-iframe-full-width-of-page

Not sure of best approach to solve but since user cannot edit source or change layout, videos are not working correctly.

Also, be really nice feature to allow editing of source code:)

Thanks for sharing your work!

**Comment by givanz** [comment]
Thanks for the suggestion, I added width and height inputs for both widget components and also code editor support.

**Comment by oleteacher** [comment]
Great!

**Comment by oleteacher** [comment]
Very nice addition for the videos!

Only issue I see is the videos are no longer responsive without extra css. No big issue since you added the code editor though:)
