### ISSUE TITLE
Where's Installation guide

### ISSUE THREAD

**Issue by salahatwa** [givanz/VvvebJs#20]
**_I got the following error when open editor.html_**
- **What;s Installation Process to use Vvvebjs**
```
Uncaught TypeError: Cannot read property 'doctype' of undefined
    at Object.getHtml (builder.js:1044)
    at HTMLButtonElement.save (builder.js:1161)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.q.handle (jquery.min.js:3)
```

**Comment by givanz** [comment]
There is no installation process, just open editor.html in your browser after cloning the repository or downloading a release.

What browser are you using?

**Comment by salahatwa** [comment]
i run it  using tomcat server and it works fine now , without server not working , thanks alot givanz
