### ISSUE TITLE
Drag and drop is not supported properly

### ISSUE THREAD

**Issue by KiranJPatel** [givanz/VvvebJs#22]
Hello @givanz ,

I am planning to use your library for creating one of my open source project related to email template builder.

It seems drag and drop; both from toolbar to content editor and control drag drop within content editor are not working as expected.

May I know which drag n drop library; you have used? Any optimization suggestion for completely replacing existing drag drop with more sophisticated drag drop or sortable libraries? i.e. interact.js etc.

I would like to implement drag drop functionality like it is there in https://www.formsite.com/ editor. It support both left->right and top->bottom drag drop in better way.

**Comment by givanz** [comment]
Hi

I didn't use any drag and drop library, it is all done with mouse events, what problems did you have with dragging and in which browsers? Maybe I can test and fix the issue.

To implement a drag and drop library many changes are needed also most if not all drag and drop libraries don't have support for dragging from parent inside iframes and it will need patching, also I see no reason for switching to a library besides better support for more devices but this can be achieved in time by fixing reported bugs.

**Comment by AhmedCIW** [comment]
> Hello @givanz ,
> 
> I am planning to use your library for creating one of my open source project related to email template builder.
> 
> It seems drag and drop; both from toolbar to content editor and control drag drop within content editor are not working as expected.
> 
> May I know which drag n drop library; you have used? Any optimization suggestion for completely replacing existing drag drop with more sophisticated drag drop or sortable libraries? i.e. interact.js etc.
> 
> I would like to implement drag drop functionality like it is there in https://www.formsite.com/ editor. It support both left->right and top->bottom drag drop in better way.

I kept the dragging and dropping components into the iframe logic as is, then inside the iframe, I used jquery ui sortable refreshed on component droop, this make it much smoother to handle after drop

**Comment by KiranJPatel** [comment]
I have taken following approach:
1. I kept the dragging and dropping components into the iframe logic as is
2. Then inside the iframe, Integrated below drag drop library which supports nice drag drop functionality without any visible flickering.
http://farhadi.ir/projects/html5sortable
