### ISSUE TITLE
On Change Event

### ISSUE THREAD

**Issue by simokassab** [givanz/VvvebJs#24]
Dear Givanz,

Look Great and useful.

But i need an auto save button or something like that, i need when i drag and drop an element to save automaticallly in my DB or to call Gethtml() function. but i need to know when i can use this function ? 

Thank you.

**Comment by givanz** [comment]
Hi

You can use undo events to save the content on every change

```javascript
Vvveb.Builder.frameBody.on("vvveb.undo.add vvveb.undo.restore", function (e) {

	var html = Vvveb.Builder.getHtml();
	alert(html);//replace with ajax call
});
```
