### ISSUE TITLE
how to integrate with ASP MVC or Orchard Core

### ISSUE THREAD

**Issue by fasteddys** [givanz/VvvebJs#242]
Hello, this is very promising, can you please share the steps to integrate this with the platform.

Also consider yourself with a list of Form Templates/Builders

**Comment by givanz** [comment]
Hi

The easiest way to integrate it into any platform is to copy the javascript and css files (/libs and /css folders) and then create a page in your platform/cms and copy the editor html code from editor.html in this page, then adjust the path to /libs /css files to point to the right location on your platform.
