### ISSUE TITLE
Widgets/ Charts / Dashboard components

### ISSUE THREAD

**Issue by fasteddys** [givanz/VvvebJs#243]
Can you please add widgets so we can also build widgets and dashboards

**Comment by givanz** [comment]
Hi

Can you please provide more details or examples on what widgets you need to build?

**Comment by fasteddys** [comment]
You have regular text components, can we add grouped components/graphs/cards

![image](https://user-images.githubusercontent.com/96149622/149607534-279a23e5-be23-4c3a-a4c0-dc9bd0d87e78.png)

**Comment by givanz** [comment]
Hi

You can create custom components and component groups for charts, you can read about creating components here https://github.com/givanz/VvvebJs/wiki/Components 

You can check the chart component code from the widgets group that is built with [chart.js](https://www.chartjs.org/) library as a starting point to built your own chart components https://github.com/givanz/VvvebJs/blob/master/libs/builder/components-widgets.js#L442-L572
