### ISSUE TITLE
jqeury not working on latest chrome

### ISSUE THREAD

**Issue by shamimsdp** [givanz/VvvebJs#25]
I'm using latest chrome 70. When I open editor.html file it shows error "Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame" but it seems fine in firefox.

![screenshot_3](https://user-images.githubusercontent.com/6303499/48248220-a437b200-e420-11e8-87ad-f1fbff9019cc.png)

**Comment by givanz** [comment]
Hi

I just tested https://vvveb.com/vvvebjs/editor.html on latest Chrome (70.0.358.77) and I can't reproduce the bug.

**Comment by givanz** [comment]
Thanks for info @oleteacher I even tried `chrome --allow-file-access-from-files` and it still doesn't work.

I didn't find any other info on how to enable iframe access on local files for chrome so the only solutions are to use a different browser or a http server.

**Comment by givanz** [comment]
@oleteacher thanks for the tips.
@shamimsdp you can try the tips provided by @oleteacher to run from files on chrome or you can switch to firefox or other browser if you are unable to run a http server. 
Chrome blocks iframe access when running from files, this is a chrome feature/issue and it can't be fixed from code.
