### ISSUE TITLE
Custom Elements and Controls

### ISSUE THREAD

**Issue by zakk616** [givanz/VvvebJs#266]
can we add custom elements and controls to this projects ?

**Comment by the-ameen** [comment]
Yes!

**Comment by givanz** [comment]
Hi

You can read a guide on how to add custom components here https://github.com/givanz/VvvebJs/wiki/Components 

Or you can start by duplicating and changing an existing component group like https://github.com/givanz/VvvebJs/blob/master/libs/builder/components-widgets.js
