### ISSUE TITLE
Blocked a frame with origin  from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by simokassab** [givanz/VvvebJs#27]
Dears,

Am having this error, when i redirect my page to the page Builder:

Uncaught DOMException: Blocked a frame with origin "my domain" from accessing a cross-origin frame.

![image](https://user-images.githubusercontent.com/16435213/49158071-fa19be80-f329-11e8-985d-1bc0e4a85f92.png)

How to solve this in Builder.js ?

**Comment by givanz** [comment]
Hi

Make sure that the page your are editing is on the same domain/subdomain as the editor, you can also add "Access-Control-Allow-Origin" header from server side https://enable-cors.org/server.html
