### ISSUE TITLE
Saved pages not showing when reload

### ISSUE THREAD

**Issue by zakk616** [givanz/VvvebJs#281]
i'm saving pages in `demo` and pages are being save, but when I'm reloading the page these pages are not being enlisted.

any solution?

**Comment by givanz** [comment]
Hi

You are adding new pages that don't show in the file manager list after refresh? 
You are probably using editor.html instead of editor.php, you need to use the php version that reads the file list inside `demo` folder.

**Comment by zakk616** [comment]
yes got it, thanks
