### ISSUE TITLE
Save dosnt work | Help please

### ISSUE THREAD

**Issue by vinumweb** [givanz/VvvebJs#282]
Hi everyone!
Im here to create a system for my customers to create and maintain theyre own website.
But i have a problem. I downloaded vvvebjs (NOT THE WHOLE CMS) from github but when i try to save it says
undefined array key, and failed to open stream: no such file or directory.

How do i fix this?
btw. Thanks alot for this amazing pagebuilder!
![image](https://user-images.githubusercontent.com/118371819/213870358-e737c93a-98cf-4558-91e2-bd57d02a4673.png)

**Comment by givanz** [comment]
Hi

From the error message it seems that `file` is not sent through ajax to `save.php`, can you please check if all parameters are sent on save in the browser `developer console` (Press F12) > `network tab`? 

It should have `file` like in the attached screenshot.

![Screenshot_2023-01-21_22-35-40](https://user-images.githubusercontent.com/302738/213886540-bc26555b-b263-4ba0-ab69-0d137431b9bc.png)

**Comment by vinumweb** [comment]
Hi. Can we please chat on discord?

**Comment by vinumweb** [comment]
And yes it does show the file

**Comment by vinumweb** [comment]
![image](https://user-images.githubusercontent.com/118371819/213886887-afb040ad-1f9e-4e71-bd79-770133744ad9.png)

**Comment by givanz** [comment]
> Hi. Can we please chat on discord?

Sorry, I don't have a discord account.

In your screenshot there is a request `save` in red at the end of the list, can you please check it? I think there are two requests made one correct and another that is missing data, the one in red.

Are the changes made to the page saved? if you refresh the page the changes persist?

Is the code unchanged? I can't reproduce this error with the code from github.

**Comment by vinumweb** [comment]
Hi. Please remain on the page. Its quite urgent. im sorry.

Yes i notices the red one too.
The page is unsaved.
Here is a pictture of the red
![image](https://user-images.githubusercontent.com/118371819/213887326-d26e3f0c-42e8-425a-9846-731b01f2ca83.png)

**Comment by givanz** [comment]
Can you also check `response` tab to see if it matches the error message that is shown in the alert to make sure that is request is causing the error?

Also please provide a screenshot with `console` tab like the one bellow for the failed request to see what code is calling this request.

![Screenshot_2023-01-21_23-15-31](https://user-images.githubusercontent.com/302738/213887497-9926e405-66c0-491b-b379-2aa5aedafea2.png)

**Comment by vinumweb** [comment]
It matches yes. And thank you for taking youre time to help me!

**Comment by vinumweb** [comment]
Here is the console
![image](https://user-images.githubusercontent.com/118371819/213887569-024d5335-59a2-44dd-b8e3-4734ee56f8cb.png)

**Comment by vinumweb** [comment]
Omg i just found out its because of my .htaccess file. IM SO SORRY MATE. Thanks for this amazing editor and have a great rest of youre day <3 love

**Comment by vinumweb** [comment]
Oh but now new problem. sorry. When i try to create a new file it gives me this:
![image](https://user-images.githubusercontent.com/118371819/213887812-5e638616-5787-4263-a039-73887c3d1f0d.png)
![image](https://user-images.githubusercontent.com/118371819/213887844-3f1dc517-0bfe-476d-9e58-8741a5c46f1e.png)

**Comment by vinumweb** [comment]
It seems that it cant create the file itself if it dosnt exist
How do i make it create it itself?

**Comment by vinumweb** [comment]
Ok. ok ok. It cant create a folder itself. How do i make it able to do that? And when i create a new page with a existing folder i save it but then when i reload the page it dosnt show up

**Comment by vinumweb** [comment]
bro im such a idiot. Im so sorry for wasting youre time. Its because i needed to open .php not .html. Tahnks for this project!

**Comment by givanz** [comment]
>  Its because i needed to open .php not .html

To load new files you need to use the php version that loads the file list.

> It cant create a folder itself. How do i make it able to do that? 

In save.php replace 

`$file = sanitizeFileName($_POST['file']);` 

with the following code

```php
$file = sanitizeFileName($_POST['file']);
$dir = dirname($file);
if (!is_dir($dir)) {
	echo "$dir folder does not exist\n";
	if (mkdir($dir, 0777, true)) {
		echo "$dir folder was created\n";
	} else {
		echo "Error creating folder $dir\n";
	}
}
```

I'm glad it works.

**Comment by vinumweb** [comment]
Hi again @givanz 
Can you please help me. How do i save the files and create a new page to a different directory.
This is how my files are

```
My-project
-customers (i want the files to be here)
-admin
--vvvebjs (here is the folder with vvvebjs all content inside)
---editor.php
---save.php (save.php should save all files to customers folder)
```


Thanks in advance.
- Peter
