### ISSUE TITLE
Delete image in media modal

### ISSUE THREAD

**Issue by ghost** [givanz/VvvebJs#294]
Can you make a commit that makes a function so the user can delete some of the photos in the modal?

Thanks

**Comment by givanz** [comment]
I will add file management features to media modal in the next update that will be made in a few days.

**Comment by givanz** [comment]
Delete and rename for media modal are available in the last commit https://github.com/givanz/VvvebJs/commit/a7fb31546165caa6a92c1b22198fb4e53f642143
