### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ghost** [givanz/VvvebJs#295]
Hi @givanz .
Thanks for the amazing project.
Im aware vvvebjs is licensed under apache 2.0 license.
I made a website administrator where user is able to make a website and customize it using vvvebjs.
Am i allowed to say "website builder made by vinumweb" I have credited you under my docs page.

 Peter

**Comment by givanz** [comment]
Hi

You can customize everything including branding.

Thanks for the credit, this is all that is needed.

**Comment by givanz** [comment]
Yes, you can say that you built your project, according to the license you only need to keep the copyright notices in the source files, in this case in the VvebJs `.js` files, of course you can also add your own notices together if you make changes to the files.

https://github.com/givanz/VvvebJs/blob/master/LICENSE#L100-L104
