### ISSUE TITLE
Can no longer save

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#3]
Updated to latest version and can no longer save. The popup is not functioning:

![image](https://user-images.githubusercontent.com/26278259/38207637-27d7913a-3674-11e8-9517-b7d386f4f3a7.png)

All the exact same on my end, only thing I did was overwrite all files with new ones.

**Comment by givanz** [comment]
There was an unclosed div in editor.html I fixed this in the latest commit.

**Comment by oleteacher** [comment]
Great job on VvvebJs!
