### ISSUE TITLE
clone element issue!

### ISSUE THREAD

**Issue by adimilyada** [givanz/VvvebJs#30]
When i clicked on a div or container at the workspace. then i tried to clone it using "clone element"...and suddently gone crazy. i just clicked it once...but i got 7-8 copies.it happens every time i use clone element.
any solution? thx

**Comment by givanz** [comment]
Hi

I'm unable to reproduce this issue, can you provide more details like browser and template used or other specific details that can help reproduce the issue?

**Comment by adimilyada** [comment]
i'm using landio template.which is already provided in the app...and my browser is chrome  ver.70.0.3
you can check in this short vid. may be this will explain alot. https://imgur.com/a/RcS7Cb8

**Comment by givanz** [comment]
Thanks for the video, I fixed the bug in the latest commit.
