### ISSUE TITLE
Custom question

### ISSUE THREAD

**Issue by domainoverflow** [givanz/VvvebJs#31]
Hi @givanz , thanks for making this amazing editor source code.
I've been trying to add a custom element, which would be a clickable picture, ex:

<    a href="some.link" >     
<   img src=""      > 
<  /a                       >
 
 

The above HTML makes the img clickable. 
I tried adding Component in the .js ( both input and components-b ) following the model in the Wiki - added the template in the indexhtml ... I can't get it to work. 
I even tried the html/link - that works ( it is off by default it seems ) but doesn't really drop properly, so I turned that off - I noticed many components available not being used in the index demo. 
I was wondering is there a more detailed example than the Wiki ? 
It would be great if the steps could be listed. 
Alternatively, I tried to wrap the img with  <   a href  >   within the component html/card but that also broke the component. 
Thanks for your time, kudos for this editor -it's the best around.
thanks!

**Comment by domainoverflow** [comment]
in another words, it would be great to see a step-by-step custom wiki instructions on adding a widget as such: 
<  a href = " some.link " >
< img src="some-image.png"     > 
<   / a    >
in practice, this creates a clickable picture ( click on the picture and the href link will happen ). 
from the wiki, I understand that we can either do this via the components or the widgets ( .js files ) and adding a template for the properties as well at the indexhtml ..  
I would appreciate if anyone could point me .. 
thanks for any help,

**Comment by domainoverflow** [comment]
@givanz

**Comment by givanz** [comment]
Hi

Thank you, make sure that the html if it spans on multiple lines has ```\``` at the end.

If you want a new group let's say Custom components you can create a components-custom.js and include it in editor.hml

```
<script src="libs/builder/components-bootstrap4.js"></script>	
<script src="libs/builder/components-custom.js"></script>	
 ```

After adding a new component inside components-custom.js

```
Vvveb.Components.extend("_base", "custom/clickableimage", {
   html: '< a href = " some.link " >\
             < img src="some-image.png" >\
            < / a >',
       ...
};
```
you also need to add it to component group 

```
Vvveb.ComponentsGroup['Custom components'] = [ "custom/clickableimage", "custom/component2",];
```

Or if you want to add the component to an existing group like bootstrap 4 just edit components-bootstrap4.js add the component code in the file and then append the name at the end of the Vvveb.ComponentsGroup['Bootstrap 4'] array 

```
Vvveb.ComponentsGroup['Bootstrap 4'] =
["html/container", "html/gridrow", ... , "custom/clickableimage"]
```

I think the easiest way is to copy an existing component that is similar as a base, change the name and add it to a group and then start making changes.
