### ISSUE TITLE
Code Editor Broken?

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#33]
Just updated from your last push.

Seems the code editor is broken. Any edits are not saved and if you tick  "Run code on edit", this error shown in dev console:

```
VM315:3 Uncaught TypeError: The element or ID supplied is not valid. (videojs)
    at t (<anonymous>:3:239)
    at htmlVideo (<anonymous>:88:5)
    at init (<anonymous>:155:5)
    at <anonymous>:161:3
    at <anonymous>:163:3
    at m (jquery.min.js:2)
    at Function.globalEval (jquery.min.js:2)
    at text script (jquery.min.js:2)
    at Ut (jquery.min.js:2)
    at k (jquery.min.js:2)
```

If it matters, using the Landio Landing Page template to test new setup. But, seems editor is not saving on any template.

**Comment by oleteacher** [comment]
@givanz Sorry for delay in response.

"Check if the file is changed on disk or load the html directly in the browser this might be a browser cache issue,"

Not for me, simply does not work. I make a change using the code editor, it ignores it. I can open / expand the code editor, make a change and it is lost no matter what I do.

**Comment by givanz** [comment]
What webserver are you using? are editor files located at the root folder of the http server? 
Can you please check if save.php is called successfully through ajax (no http error) and that demos/ folder and inside files are writable by php/webserver? (you can set 777 full permission for testing) you can also add some debugging inside save.php like 

```
var_dump($fileName);

```

before 

```
if (file_put_contents($fileName, $html)) 
```
And then check the ajax output in developer tools to see that the filename and path is correct.

**Comment by oleteacher** [comment]
Thanks much for all your help. I think what was happening was server was caching and took some time to catch up with the updates / mods I had made.

Seems to be working fine now.

Cheers!
