### ISSUE TITLE
text editor undo is not working 

### ISSUE THREAD

**Issue by AngelinaShoiliRozario** [givanz/VvvebJs#354]
![image](https://github.com/givanz/VvvebJs/assets/89296049/c2262c09-8962-42fa-a8a4-95e2f77ac602)

![image](https://github.com/givanz/VvvebJs/assets/89296049/980cdc1f-87f4-4b02-8989-7ed70e8650be)

**Comment by givanz** [comment]
Can you please provide steps to reproduce? 

By simply changing some text on the page and using undo it does not generate the error.

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the last commit https://github.com/givanz/VvvebJs/commit/e122685e7c99eb84db5cb3a495eefc970a74a429
