### ISSUE TITLE
Non php version

### ISSUE THREAD

**Issue by wisamidris7** [givanz/VvvebJs#356]
Can you make a version or branch for non php version cause i really need it a application without php cause i hate it?
Or tell me if i can replace it in my local instance only.

**Comment by givanz** [comment]
Using php is optional and is only included for server side page save example.

You can also use node https://github.com/givanz/VvvebJs/blob/master/save.js 

Or you can use any backend service by changing the save url https://github.com/givanz/VvvebJs/blob/master/editor.html#L72

On save a POST request is made to `data-vvveb-url` with the following parameters: 

* **file** - path and filename 
* **action** - can be save/rename/delete/saveReusable/oembedProxy
* **startTemplateUrl** - if a new page is created the template file to use
* **html** - the html content of the edited page

**Comment by wisamidris7** [comment]
Thanks i understood it after i read the save.js code cause i think start.js or main.js would be more understandable!
👍
