### ISSUE TITLE
How to architect something like Vvvebjs

### ISSUE THREAD

**Issue by sushant12** [givanz/VvvebJs#36]
You have built an amazing web builder and I am also on the verge of building a very very very simple builder. I have few questions which I hope you will clear.

How does the web builder know what div to make editable? Do we have to specify some id or something to make js aware that the particluar div is editable or place to drop components???

A user will edit a original html template. After he is finsihed, does the web builder generate html, css and js or will it save the structure information in json and save it to db then later fetch the json and map the changes???

**Comment by givanz** [comment]
Hi

Thank you.

VvvebJs has a very simple architecture, for editing click and double click events on the iframe are registered.

On click the element that has been clicked is checked against registered components and if it matches any of them then the component properties are loaded in the right column.

On double click the content editable attribute https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content is added to the element and the text toolbar is shown.

No processing is done on html before to add attributes or any other changes, the html is preserved as it is, all elements are editable.

Elements can be dropped on any component in the iframe, there is no checking, this responsibility is passed on the browser that will take care of not allowing it on certain elements if it's the case.

The builder does not generate html, when save button is clicked the iframe html is shown in a modal without any processing, if saveAjax is used then the html is sent through ajax to be saved on the server, to enable server saving check https://github.com/givanz/VvvebJs/issues/28#issuecomment-447365081

The editor is very simple and has only 1475 lines of code without components, you can easily understand how it works https://github.com/givanz/VvvebJs/blob/master/libs/builder/builder.js

**Comment by sushant12** [comment]
thanks mate. I appreciate it
