### ISSUE TITLE
"landing" folder in "demo" folder tree is completely empty?

### ISSUE THREAD

**Issue by roschler** [givanz/VvvebJs#382]
I have my VvvebJs project folder set up.  I am using `http-server` on Windows 10 to run the editor.  I launch the editor using:

http://localhost:3000/editor.html

and the visual editor appears on the screen.  However, when I try to drag components from the left sidebar to the canvas they get "stuck" in the left sidebar.  In other words, I can't drag the icon outside the frame of the left sidebar and when I let go of the mouse, the component icon just stays where I stopped moving it like a "ghost" icon.

![image](https://github.com/user-attachments/assets/c92309bc-0dee-4bc7-a1bc-fc309926bc52)

I looked in Chrome DevTools and these two files are missing (Not Found):

./demo/landing/sections/sections.js

./demo/landing/index.html?r=0.31538089256001234

I checked the `demo` folder in the GitHub repo and they are there.  But after the cloning operation the `landing` folder on **my** hard disk is completely **empty**.

Just to be sure I repeated the sub-modules pull command again:

_git pull --recurse-submodules_

And like the first time it said "Already up to date".

But I checked again my entire hard disk after cloning the repo and nowhere is there a `sections.js` file and the `./demo/landing` folder is still empty.

Note, just to be sure, I tried downloading the repo as a zip and then expanding it but the `landing` folder is still empty:

![image](https://github.com/user-attachments/assets/c99621a9-4992-41ba-aa78-5329ada910d5)

So why is the `./demo/landing` folder on my hard disk empty?  Was a recent change made to either `.gitignore` or `.gitattributes` that might be interfering with an attempt to clone or download the repo?

**Comment by givanz** [comment]
You also need to use `--recurse-submodules` when cloning 

```bash 
git clone --recurse-submodules https://github.com/givanz/VvvebJs
``` 
to avoid getting the empty folder, `git pull --recurse-submodules` will not work otherwise.

**Comment by roschler** [comment]
Thanks!  That worked great.
