### ISSUE TITLE
Option to  create an Ordered List

### ISSUE THREAD

**Issue by maheshwaricharu** [givanz/VvvebJs#386]
Hi there
Please confirm if editor gives an option to create an ordered List using Components. I can see Unordered list in the Components, is there an option to create "ol" tag too using editor.
Alternatively, can we achieve the same using CSS styles, list 
`{ 
   list-style-type: number;
}` 
I can see there is an option to use List component, however it is not working, so cant be sure of its Usage.
![image](https://github.com/user-attachments/assets/3818026d-de54-4c9c-803a-634418704dfa)

**Comment by maheshwaricharu** [comment]
@givanz Request you to provide some suggestion on the same.

**Comment by givanz** [comment]
Hi

The option to switch from unordered to ordered list was added in the last commit https://github.com/givanz/VvvebJs/commit/409ede1a720b1d0cd2939f625d0065645db163dc you can check the feature on the demo https://www.vvveb.com/vvvebjs/editor.html

**Comment by maheshwaricharu** [comment]
Thank you for your prompt response.
