### ISSUE TITLE
How to change bacground image?

### ISSUE THREAD

**Issue by netforcelabs1** [givanz/VvvebJs#39]
Hi,

I have few templates where in html we have used background images.

Can you please tell me how to add ability in the editor so that users can change their background image?
Also is there any instructions to add our own template? Have you used any common css classes which needs to use in all pages.

Looking forward for your early response!

**Comment by givanz** [comment]
Hi

To add your own templates please check the last lines in editor.html where the editor is loaded, there you will see how the demo templates are loaded using FileManager

```js
	Vvveb.FileManager.addPages(
	[
		{name:"narrow-jumbotron", title:"Jumbotron",  url: "demo/narrow-jumbotron/index.html", assets: ['demo/narrow-jumbotron/narrow-jumbotron.css']},
		{name:"landio", title:"Landio landing page",  url: "demo/landio/index.html", assets: ['demo/landio/landio.css']},
		{name:"album", title:"Album",  url: "demo/album/index.html", assets: ['demo/album/album.css']},
	]);
	
	Vvveb.FileManager.loadPage("narrow-jumbotron");//load a certain template when the editor page loads
```

If you have css that you want to add to every page then you can inject it in the page after the iframe is loaded

```js
Vvveb.Builder.documentFrame.on("load", function (e) { 
   Vvveb.Builder.frameBody.append("<style>#id {color:red}</style>");//inline
   Vvveb.Builder.frameBody.append("<link rel="stylesheet" href="my.css" />");//external
});
```

Image background is the last option in the right panel

<a href="https://imgur.com/a/Fd5KGcd"><img src="https://i.imgur.com/uHSAQpl.png"></a>
