### ISSUE TITLE
Question Configure  Non editable html elements

### ISSUE THREAD

**Issue by lookingdown** [givanz/VvvebJs#42]
Thanks for great script...
I am loading html with editable and non editable elements.
The non editable are script generated like post galleries and product galleries and the likes..

Is there a way to define a class like "not-editable" for div or section tags that prevents triggering of wysiwyg editing for these elements ?  Thought I might ask instead poking around and perhaps reinventing the wheel..   
The purpose of this is to give some indication to users that certain elements are not editable... by NOT hightlighting them  , the NOT editable content will not be saved as it is dynamically generated.. on every page load.   

The html generated is parsed and only content that is editable will be saved indicated by data-* attributes.. 
 and working well. :)

Static display no editor no highlight  for this.. (could be class or data-attribute selector)
```
    <section class="not-edit"> 
     No parsing of tags here.. no Static display no editor no highlight  for this..
    </section>
```

**Comment by catalin87** [comment]
I can help you defining editable region on a page, maby will help:

Just go to builder.js at line 711
Comment the line: 
`// self.frameBody = $(window.FrameDocument).find("body");`
and add:
`self.frameBody = $(window.FrameDocument).find("#editableContent");`

Now, in your loaded HTML make a div with **id="editableContent"** , you will be able to edit only what is inside that div.

**Comment by lookingdown** [comment]
Awesome, Thanks!

**Comment by givanz** [comment]
Hi

I added support for non editable areas in the last update, to make an element non editable just add **data-vvveb-disabled** attribute

```html
<div data-vvveb-disabled></div>
```

**Comment by lookingdown** [comment]
Way to Go ..
Thats a Very useful feature.
Thanks a lot

**Comment by kerepuki** [comment]
Thank you for an amazing script. I've started using the data-vvveb-disabled however I am still able to double click into the elements that have this attribute. Am I missing something else?

**Comment by givanz** [comment]
Mouse events bubble to parent and when clicking or double clicking on disabled elements then the parent is selected or double clicked.

You can replace 

```javascript
if (Vvveb.Builder.isPreview == false) {
```
with 

```javascript
if (Vvveb.Builder.isPreview == false && !event.target.querySelector("[data-vvveb-disabled]")) {
```

in https://github.com/givanz/VvvebJs/blob/master/libs/builder/builder.js#L1561 and https://github.com/givanz/VvvebJs/blob/master/libs/builder/builder.js#L1600

this will prevent click or dbl click to work on parent elements that include disabled child elements, the down side is that it will apply to other child elements that are not disabled.

To make it properly work there should be some element checking based on mouse x and y coordinates and see if the clicked element is indeed disabled or not.
