### ISSUE TITLE
New page, add blocks issue

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#44]
Greetings Givan, hope you are doing well!

I was trying new release on your example site and ran across this issue:

https://www.useloom.com/share/7ff97d8bf2424292a0063d376b338fe4

There were no errors shown in DEV console or would also post those.

Also when trying out "blocks - slider" can not find way to replace image? Once dragged over and clicking on element, cannot see options.

Running Win 10 Pro and latest Chrome.

Susan

**Comment by fauzie** [comment]
+1

**Comment by givanz** [comment]
Hi

Thanks for reporting the bug, this was fixed with a pull request https://github.com/givanz/VvvebJs/pull/45
The image from the snippet is set with in css with background-image and can be changed from background image section.

**Comment by oleteacher** [comment]
Wonderful, thank you @givanz and @haikarthikssk!

Something else you may wish to change is the direct linking to startbootstrap. On my tests, they seem to block and all I see are broken images (on our local network at school).

`<li data-section="Bootstrap 4 Snippets" data-drag-type="block" data-type="bootstrap4/signin-split" data-search="modern sign in page with split screen format" style="background-image: url(&quot;https://startbootstrap.com/assets/img/screenshots/snippets/sign-in-split.jpg&quot;); background-repeat: no-repeat;"><a href="#">Modern Sign In Page with Split Screen Format</a></li>`

**Comment by givanz** [comment]
Images from startbootstrap are loading on my demo https://www.vvveb.com/vvvebjs/editor.html from my computer, can you try from a different network? 

I didn't want to include the images in the repository to keep it simple, current blocks were added as quick example to show how blocks work and I will probably replace them with some more functional examples in future updates.

**Comment by oleteacher** [comment]
No problem sir, totally understand. All good. We will find a solution to make work on school network.
