### ISSUE TITLE
Open for contributor?

### ISSUE THREAD

**Issue by krisnaw** [givanz/VvvebJs#46]
Hi, just wonder if this project is open for a contributor? I'd like to contribute. 
Cheers.

**Comment by givanz** [comment]
Hi

You are welcome to contribute.

The only requirement is to keep it simple, as you might have seen from the code there are minimal dependencies no external drag and drop library, fancy scrollbars, colorpickers etc (using html5 inputs instead) and using only jQuery and Bootstrap 4. 

You can add external libraries but as plugins, for example codemirror  that is used for the code editor is added with a plugin to keep the core clean (the code editor will degrade gracefully and work as textarea without the plugin).

I plan on adding more events to make adding plugins easier in future updates.
