### ISSUE TITLE
Filemanager

### ISSUE THREAD

**Issue by baldolfo** [givanz/VvvebJs#47]
Hi Givanz .....Please... 
when I create a new page it does not appear in filemanager when I reload editor.html
Regards Adolfo

**Comment by givanz** [comment]
Hi

To enable loading created html files you will need to rename editor.html in editor.php and then go to the end of the file beginning with line 838 and remove the comments around the php code there.

**Comment by baldolfo** [comment]
But my file end line 770….

 

Da: Givan [mailto:notifications@github.com] 
Inviato: sabato 23 febbraio 2019 21:39
A: givanz/VvvebJs <VvvebJs@noreply.github.com>
Cc: baldolfo <adolfo@uniphoto.it>; Author <author@noreply.github.com>
Oggetto: Re: [givanz/VvvebJs] Filemanager (#47)

 

Hi

To enable loading created html files you will need to rename editor.html in editor.php and then go to the end of the file beginning with line 838 and remove the comments around the php code there.

**Comment by givanz** [comment]
This was added in the last update a few minutes ago, you will need to update your code.

**Comment by baldolfo** [comment]
Thanks ... it works ... I had old version. Now is Ok

 

 

Da: Givan [mailto:notifications@github.com] 
Inviato: sabato 23 febbraio 2019 22:09
A: givanz/VvvebJs <VvvebJs@noreply.github.com>
Cc: baldolfo <adolfo@uniphoto.it>; Author <author@noreply.github.com>
Oggetto: Re: [givanz/VvvebJs] Filemanager (#47)

 

This was added in the last update a few minutes ago, you will need to update your code.

**Comment by junxinhuang21** [comment]
hi ,
i want to ask if need to save the html files ,except the below action ,when click the export button, the request action of saveAjax have fileName param, it have any use when this param send to Background developer?

**Comment by baldolfo** [comment]
Hi ... I think I did not understand ... vvvebjs saves the file in html

**Comment by givanz** [comment]
Hi

@junxinhuang21 not sure what you are asking, fileName param can be useful when saving the file on disk if saving in db then this can be ignored if not needed.

@baldolfo saveAjax calls save.php by default, you can call other server side script inside saveAjax or change save.php content to save to db or somewhere else.
