### ISSUE TITLE
Hover add element

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#48]
Been reluctant to open issue, as not sure it is issue and will feel like big dummy. But cannot figure out...

When hovering over items a + sign appears and says "Add Element". Clicking does nothing. What is this and how to use?

Sorry to open issue for this, but just have to know:)

Thanks!

**Comment by givanz** [comment]
Sorry for the confusion, this feature is not yet finished and I didn't want to revert the changes when pushed "non-editable element" feature.
