### ISSUE TITLE
Adding New Page

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#49]
Really like the idea of adding new page.

Can it easily be changed to add page to chosen folder? For example, add to the "/demo/album" folder instead of just /demo.

If working in certain folder be nice to add page to that specific folder.

Also being able to delete pages added be very helpful.

BTW: kids in classroom just love using and learning from vvvebJs!

**Comment by givanz** [comment]
I changed the regex for add new page filename to allow / for typing full paths.
You can now enter demo/narrow-jumbotron/test-page.html to save the file in a folder.

File manager does not currently have folder support, all listings are for files, I will add delete option in a future update.

Glad to hear that :)

**Comment by oleteacher** [comment]
Thanks @givanz !

It works, sort of. When creating a new page you must enter "demo/<template name>/page-name.html". At first could not get to work as entering "<template name>/page-name.html".

The page is created and initially shown under the pages menu. But, after VvvebJs is reloaded, page disappears from pages menu and no way to edit again?

Maybe I am just not understanding how to use:)

**Comment by givanz** [comment]
Hi

To load saved pages in file manager you need to rename editor.html to editor.php (if you use php on your server) and then uncomment php code starting from line 836, the php code will only load html files in the root folder, you might need to tweak the php code to load also html files inside subfolders by changing glob pattern and remove the default pages from addPages.

**Comment by oleteacher** [comment]
Thanks @givanz, appreciate your help.

Had already uncommented the code out and can edit the .html page just fine. The issue is once vvvebjs is reloaded. page is moved into folder and no way to expand folder to edit again.

**Comment by oleteacher** [comment]
My bad @givanz , early here and have not had enough coffee:)

"you might need to tweak the php code to load also html files inside subfolders by changing glob pattern and remove the default pages from addPages."

Will look into this and see if can figure out.

**Comment by oleteacher** [comment]
Never got it solved. The kids love using but we have had to disable for now. Will revisit at a later date.

**Comment by junxinhuang21** [comment]
hi gibanz,
i want to know new version add 'add new page' function, but when add too much ,i want to delete some pages ,could you tell is it possible to add delete function

**Comment by nikhilkhadgi** [comment]
I think I have figured out the issue. Make sure you edit the file builder.js in location VvvebJs-master\VvvebJs-master\libs\builder.js.

Steps:
1. Make sure you have uncommented php code in editor.html and renamed it to editor.php. (Note that the file should be running in a php server)
2. Go to line number 1596 of builder.js
3. Edit the code as follows:

var data = { "title": title, "url": url };
Vvveb.FileManager.addPage(name, data);

(https://user-images.githubusercontent.com/19900709/75879522-a3ac0180-5e43-11ea-86e0-be5137e525d4.png)

3. Now try to create new page. It should work now.

**Comment by Charliegrillo** [comment]
excuse me, but it doesn't work

**Comment by oleteacher** [comment]
> I think I have figured out the issue. You have to edit the file builder.js in location VvvebJs-master\VvvebJs-master\libs\builder.js.
> 
> Steps:
> 
> 1. Make sure you have uncommented php code in editor.html and renamed it to editor.php. (Note that the file should be running in a php server)
> 2. Go to line number 1596 of builder.js
> 3. Edit the code as follows:
> 
> var data = { "title": title, "url": url };
> Vvveb.FileManager.addPage(name, data);
> 
> (https://user-images.githubusercontent.com/19900709/75879522-a3ac0180-5e43-11ea-86e0-be5137e525d4.png)
> 
> 1. Now try to create new page. It should work now.

Thanks for the tip. I tried your mod and not seeing it work. Matter of fact did not see a new page created at all in menu, but does show up in main directory.

**Comment by nikhilkhadgi** [comment]
Can you provide screenshot of the page after you click on 'Create Page' button? Please share the screenshot of corresponding error log on the browser console as well.

For reference, I have a working setup of the library in this [URL](http://nikhilkhadgi.pro/vvvebjs/).

**Comment by nikhilkhadgi** [comment]
Can you provide screenshot of the page after you click on 'Create Page' button? Please share the screenshot of corresponding error log on the browser console as well.

For reference, I have a working setup of the library in this URL.

Note that in the url above, new file will be created after clicking on 'Create Page' button. However, you will not be able to save changes after editing that page due to missing permission of editing files for other users in my web server. This will not be a problem for your local server.

**Comment by oleteacher** [comment]
> Can you provide screenshot of the page after you click on 'Create Page' button? Please share the screenshot of corresponding error log on the browser console as well.

Wonderful work, I see yours working. Some errors about missing files in console log, but works to create page/folder.

I am traveling and away from my localhost. Will return next week and get a screenshot with errors (if any).

Thank you!

**Comment by xenonfactory** [comment]
Hello everybody!

It's my first comment on Github :-)

Apart from wanting to thank this incredible editor, I want to contribute my experience solving the issue discussed in this thread.

I searched the file "builder.js" for the line:

`Vvveb.FileManager.addPage (name, title, url);`

And I have replaced it with these two:
```
var data = {"title": title, "url": url};
Vvveb.FileManager.addPage (name, data);
```

As indicated by the comrade nikhilkhadgi.

Messages keep appearing on the console, but saving new files I created works. I share with you a screenshot: https://i.snipboard.io/GAJRVd.jpg

Also, explain that I have commented on all the demonstration pages because I did not need them.

I hope this works for everyone.

A greeting from Spain!

**Comment by Pratik-Hub** [comment]
Hi. I can create new pages but after creating it I can't open it please help???

**Comment by Charliegrillo** [comment]
> Hi. I can create new pages but after creating it I can't open it please help???

rename editor.html to editor.php, save el file and reopen.

**Comment by Tuna656** [comment]
2021 y aun no funciona
