### ISSUE TITLE
HOW TO CREATE MY OWN CUSTOM WIDGETS

### ISSUE THREAD

**Issue by connectpritam** [givanz/VvvebJs#5]
I want to create a custom widget/ component to let user insert a graph based on certain data. The data as of now I want to pull from a specific API. Please can you provide a wiki, or guide about how to do it.

**Comment by givanz** [comment]
Hi

You can find information about components in the wiki here https://github.com/givanz/VvvebJs/wiki/Components

You can easily learn how to add new components by checking existing components code in components-widgets.js or components-bootstrap4.js

I added a new chart.js component that you can use as a starting point, you can find the code in libs/builder/components-widgets.js

```
Vvveb.Components.extend("_base", "widgets/chartjs", {
    name: "Chart.js",
}
```
