### ISSUE TITLE
Demo drag/drop not functional

### ISSUE THREAD

**Issue by danyj** [givanz/VvvebJs#52]
Not sure if you know but the demos do not work in any browser. 
The drag gets locked https://monosnap.com/file/wDhGEgxuewbNH1IX0astnnhFUARIti

**Comment by oleteacher** [comment]
It does act funny and not right, but try continuing to drag to top of page. Seems you can then drag around the page.

**Comment by givanz** [comment]
Thanks for the detailed bug report, I fixed it in the latest update.
