### ISSUE TITLE
Absolute positioning and Resizing

### ISSUE THREAD

**Issue by MACscr** [givanz/VvvebJs#53]
Any chance we could have true absolute positioning by simply dragging the element and it correctly setting its left/right/bottom/top in relation to its container? Also, how about the ability to simply ressize an element such as a button or input field by dragging the corner and resizing it? This is a great feature of the Silex editor, but Im really hoping to have a more polished editor such as yours.

**Comment by givanz** [comment]
Hi

Thanks for the suggestion, I added designer mode in the latest update, you can enable it from top toolbar near undo buttons.

**Comment by MACscr** [comment]
Ive tried dragging items around in designer mode, but they really seem to jump around. running latest Chrome on OSX. I think its because when dragging, other elements are being outlined, which wouldn't happen when in design mode. 

I also don't see a way to drag to resize elements. Would think a bottom corner resize item on the right would make the most sense as thats where people expect it. Possible? If we can get this all working smoothly, this would be perfect for my project.

**Comment by givanz** [comment]
I fixed the jumping issue, regarding resize feature this might be added on a future update, currently is not a high priority feature.

**Comment by khalifagates** [comment]
Resize and dragging will be a novelty, in this case, it will make it more user-friendly
