### ISSUE TITLE
Animation Script is Broken after saved 

### ISSUE THREAD

**Issue by loaiabdalslam** [givanz/VvvebJs#54]
There is something strange that happened a little while ago when I was trying to save HTML File . There are some offices that we use in animation for some sections which may generate elements after loading the page when you save those elements again after modifying the html page, it generates an error in animation and spoils the design afterwards .
We want a solution to solve this problem, please because this way we are required to use static pages without animation libraries

**Comment by givanz** [comment]
Hi

The editor does not change javascript code or make any pre-processing also save/export only saves html code maybe missing javascript files can cause the errors.

You can check for javascript errors with browser developer tools (F12 key) to try to isolate the issue, you can also try a different browser.

**Comment by loaiabdalslam** [comment]
I do not mean that there are libraries generate HTML when loading the page to work with the additional accessories when loading the page using these libraries, a new HTML is generated, the idea here is that the new HTML is saved and here javascript animation is broken!
try using revolution slider with a static page and you will get what i mean

**Comment by givanz** [comment]
The easiest thing to do is to disable the javascript from running inside the editor so it doesn't change the html code, for this you can simply check if the page is loaded in a iframe (the editor loads the page in an iframe)

```javascript
var isInsideIframe = (window.self !== window.top);
if (!isInsideIframe) 
{
 initRevolutionSlider();
}
```

**Comment by percy2017** [comment]
When saving the HTML, after editing, the new HTML has a style css, which does not load.

How do I take it off?
