### ISSUE TITLE
how to load the pages from server afford?

### ISSUE THREAD

**Issue by junxinhuang21** [givanz/VvvebJs#56]
hi givanz,
  As I know the editor, when we edit the pages ,send the html code to server . so I suggest add a option for when the server afford back the html code , we can load the code and open the pages? or currently we have this function?  thanks

**Comment by givanz** [comment]
Hi

Saving the page to server works if you enable ajax https://github.com/givanz/VvvebJs/issues/28#issuecomment-447365081 if you want to load newly added pages then you can use php to load the new pages in the file manager for this you can check https://github.com/givanz/VvvebJs/issues/47#issuecomment-466691623
