### ISSUE TITLE
New Element Feature

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#59]
The new element feature is cool! Really like it.

Seeing some issues (tested demo on your site). Using Win 10 Chrome (latest).

In the below video, you will see that I click some element buttons and nothing happens. Then I scroll back to top and add the video element. Seems to work. But if I add another by clicking below video, the elements modal is not accessible.

https://www.useloom.com/share/2769132248fc4e9982ac2abc0ac56188

Thought you might like to see this.

Thanks for your work on this project!

**Comment by oleteacher** [comment]
Did not mean to close this as real issue or at least on Chrome browser.

**Comment by givanz** [comment]
Thanks for the video, I just fixed this in the latest update.

**Comment by oleteacher** [comment]
Works great now, thanks!
