### ISSUE TITLE
Question: How to ask for additional params onDrop ?

### ISSUE THREAD

**Issue by ashwinputhige** [givanz/VvvebJs#6]
I am trying to create a "data-table" component which shows records from a database table. I am thinking of creating a `htmlAttr: "data"` and use that to accept tablename on the right panel(`For eg: data-tablename="users"`). But I can't figure out how to modify the HTML after user enters tablename.

Do you have any suggestions on how this can be implemented?

Thanks in advance.

**Comment by givanz** [comment]
Hi

You want to edit data-tablename attribute for `<table data-tablename="users"></table>`?
You only need to set htmlAttr: "data-tablename"

```js
Vvveb.Components.extend("_base", "mycomponent", {
    name: "My component",
    image: "icons/mycomponent.svg",
    html: '<table data-tablename="users"></table>',
    properties: [{
        name: "Name",
        key: "name",
        htmlAttr: "data-tablename",
        inputtype: TextInput
    }]
});
```

**Comment by ashwinputhige** [comment]
ok, got it. Thanks.
