### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#66]
Having some issues using the color picker (like when changing text color). Seems to work fine on Windows machines but kids at school use Chromebooks. Could be the school antivirus and/or filewall, but color picker refueses to work.

Maybe you could point me in right direction to replace with a bootstrap pikcer? Here is really good one (or at least worked great in one of our projects):

https://github.com/farbelous/bootstrap-colorpicker

Any help/input greatly apprecaited. The kids love using VvvebJs and without colors, life is dull:)

**Comment by givanz** [comment]
Hi

I added bootstrap color picker input in the last update, you will need to edit editor.html and uncomment colorpicker scripts

```html
<!-- bootstrap colorpicker //uncomment bellow scripts to enable -->

<script src="libs/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<link href="libs/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet">
<script src="libs/builder/plugin-bootstrap-colorpicker.js"></script>

```

**Comment by oleteacher** [comment]
Outstanding, thank you so much! We were close when trying to add, but missed one of the steps.

You will be a hero next time kids use VvvebJs:)
