### ISSUE TITLE
Add element staying on test page

### ISSUE THREAD

**Issue by oleteacher** [givanz/VvvebJs#69]
Hey Givan.

Trying out latest release and noticed an issue.

For instance, you are on the jumbotron page, scroll down to "test page"and click it. The java alert appears and you click ok. If your mouse is in area that "add element" outline is shown, the test page also shows it.

![image](https://user-images.githubusercontent.com/26278259/57594153-57828000-7504-11e9-935c-6dec0dbfe83e.png)

Hope I am explaining it well:) If not can make a loom video tomorrow.

Thanks for all  the hard work!

**Comment by givanz** [comment]
Hi

Thanks for the bug report, I fixed it.

**Comment by oleteacher** [comment]
Your a good man Mr Givanz!
