### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by gauravkamath** [givanz/VvvebJs#7]
Hi,

Good day to you 👍 

I am not able to run this project on **IE 11**.  I tried fixing few of the code errors but the drag and drop still fails. When i drag & drop a component, there is no change in the code editor neither is the component rendered on iFrame. Do you have any idea about what the problem could be?

**Comment by givanz** [comment]
Hi

The issue is related to appending elements to iframe.
In ie11 console I see 'Unable to get property "createDocumentFragment" of undefined or null reference' in builder.js line 665/668 this is not transparently handled by jQuery append/prepend etc so it will probably require a new append function that has hacks for ie, unfortunately I'm unable to find any reference to what hack ie11 needs to achieve this.

**Comment by gauravkamath** [comment]
Thank you Givanz. Please update me if you do find a hack for IE 11. 
Any help is much appreciated. 💯

**Comment by gauravkamath** [comment]
Hi Givanz,

I could make the drag & drop work in IE. The issue mentioned by you was being caused because of the wrong parent element. Somehow parent = self.highlightEl; did not work and as a result parent.append would break. I tried using  $(self.highlightEl).append(self.dragElement); directly and drag & drop now works.

The code editor is still not working and i am working on finding a solution for that. will keep you updated if i find any solution for it.

**Comment by givanz** [comment]
Thanks for the fix, I just tested and it works even if not as smooth as on chrome/firefox but this is probably caused by slower js/render engine.

I tested code editor on ie11 win7 virtual box and it works, what problems do you have with the editor and what platform are you using?

**Comment by gauravkamath** [comment]
Well neither drag & drop nor the the property window changes reflect anything in the code editor.

I am trying it on IE 11 in windows 10.

**Comment by givanz** [comment]
I fixed property change and also pushed the changes for ie11.

**Comment by gauravkamath** [comment]
Thank you so much Givanz 💯 👍
