### ISSUE TITLE
Add new option to component properties advance tab for HTML Tag

### ISSUE THREAD

**Issue by farhankhalid287** [givanz/VvvebJs#74]
Hi, 
is there any option to add new option to component properties panel for specific HTML tag like button tag and on user action set the appropriate value

**Comment by givanz** [comment]
Hi

To add new component properties is very easy.

To add a component for <button> all you need is 

```js
Vvveb.Components.extend("_base", "html/button", {
    nodes: ["button"],
    name: "Button",
    image: "icons/button.svg",
    html: '<button>Button</button>',
    properties: [{
        name: "Text",
        key: "text",
        htmlAttr: "innerHTML",
        inputtype: TextInput
    }, {
        name: "Name",
        key: "name",
        htmlAttr: "name",
        inputtype: TextInput
  }]
});
```

Nodes specifies the tags to link the component to specific tags and properties defines  the inputs for component.

To make the component visible in the drag components panel you also need to register it to a component group, for example for Bootstrap 4 you need to add it to the existing list like this

```js
Vvveb.ComponentsGroup['Bootstrap 4'] =
["html/container", ..........,  "html/button"] 
```

For more options check https://github.com/givanz/VvvebJs/wiki/Components  or check existing components in libs/builder/components-bootstrap4.js

**Comment by farhankhalid287** [comment]
Hi , first of all sorry for late reply. It was my bad , i dont understand documentation well. Thanks for the Help :+1:
