### ISSUE TITLE
Issue with Slider, not running/non editable throw js error on click

### ISSUE THREAD

**Issue by aloksharma1** [givanz/VvvebJs#76]
Hello,

To replicate the issue, go to new page or on same page add bootstrap block "Image Slider Header". 
go to preview or click the carousel navs on left/right or bottom. the slider doesnt scroll , hence user cannot modify anything after first slide. even in preview its not working and the only way to change anything is code editor..

js error on click :
```
Uncaught TypeError: Cannot read property 'html' of undefined
    at Object.setHtml (builder.js:1325)
    at plugin-codemirror.js:24
    at codemirror.js:2143
    at fireCallbacksForOps (codemirror.js:2100)
    at finishOperation (codemirror.js:2114)
    at endOperation (codemirror.js:3736)
    at runInOp (codemirror.js:3865)
    at handlePaste (codemirror.js:8068)
    at HTMLTextAreaElement.<anonymous> (codemirror.js:9204)
```
awaiting your findings..

**Comment by givanz** [comment]
Hi

It works fine for me, tested on chrome, dragged the component on default "Landing page" the next/prev works in preview but in the editor the button element is selected instead of next action as expected.

Please note that blocks used in the blocks section are just some examples taken from start bootstrap and are added to showcase the editor block features.

**Comment by aloksharma1** [comment]
ok, i checked the live link is working but the github copy i downloaded to local is not working correctly. is it missing some updates from your end?
thanks

**Comment by aloksharma1** [comment]
ok, i checked the code of landing page in editor samples it was missing the js part to run the slider, but it worked to about us page. still would like to see if we can change slider pics without shifting b/w preview and editor modes.
thanks
