### ISSUE TITLE
support bootstrap template?

### ISSUE THREAD

**Issue by xiaochun995** [givanz/VvvebJs#8]
hi may i ask got function support to import the bootstrap template?

**Comment by givanz** [comment]
Hi

You mean to upload a complete template with html/css and js files? For this you will need a little backend (php/python/ruby etc) script to save (unzip if necessary) the files somewhere on the server and then load the html file in the editor.

For html only you can paste the html directly in the code editor.

**Comment by marcocesarato** [comment]
I've done a version (it need to be adapted) that when you save or onmouseleve it transmit into a textarea the code of template. I ve a backend panel after where you save the field of the textarea. I dont know it is this what you meaning.
